service: note-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  api:
    handler: src/index.handler
    environment:
      TABLE_NAME: !Ref ShoppingTable
    events:
      - http:
          path: /
          method: get
  addItem:
    handler: src/addItem.handler
    environment:
      TABLE_NAME: !Ref ShoppingTable
    events:
      - http:
          path: /add
          method: post
    timeout: 30
  getList:
    handler: src/fetchList.handler
    environment:
      TABLE_NAME: !Ref ShoppingTable
    events:
      - http:
          path: /fetchList
          method: get
    timeout: 30
  updateItem:
    handler: src/updateItem.handler
    environment:
      TABLE_NAME: !Ref ShoppingTable
    events:
      - http:
          path: /updateItem
          method: post
    timeout: 30
  deleteItem:
    handler: src/deleteItem.handler
    environment:
      TABLE_NAME: !Ref ShoppingTable
    events:
      - http:
          path: /deleteItem
          method: post
    timeout: 30

resources:
  Resources:
    ShoppingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage}-ShoppingList
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
          