service: note-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
  addItem:
    handler: src/addItem.handler
    events:
      - http:
          path: /add
          method: post
    timeout: 60
  getList:
    handler: src/fetchList.handler
    events:
      - http:
          path: /fetchList
          method: get
    timeout: 60

resources:
  Resources:
    ShoppingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ShoppingList
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
          