name: Deploy on main i.e. prod environment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  DeployServerless:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with: 
        persist-credentials: false
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install
      run: npm install
    - name: Serverless deployment on prod
      if: endsWith(github.ref, 'main')
      uses: serverless/github-action@master
      with:
        args: deploy --stage prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    - name: Serverless deployment on dev
      if: endsWith(github.ref, 'dev')
      uses: serverless/github-action@master
      with:
        args: deploy --stage dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        
    
